receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  # filter/health:
  #   error_mode: ignore
  #   traces:
  #     span:
  #       - 'name == "GET /health"'
  # attributes/add-environment:
  #   actions:
  #     - key: environment
  #       value: development
  #       action: upsert
  # attributes/remove-route:
  #   actions:
  #     - key: http.route
  #       action: delete

exporters:
  otlp:
    endpoint: "aspire-dashboard:18889"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [
          batch,
          # filter/health,
          # attributes/add-environment,
          # attributes/remove-route,
        ]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
