services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    ports:
      - 18888:18888
      - 4317:18889
  seq-node01:
    image: datalust/seq:latest
    container_name: seq-node01
    restart: unless-stopped
    ports:
      - "5341:5341"
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data01:/data
volumes:
  seq-data01:
